<h1> Final Project For Submission in Python for Data Science</h1>

In [1]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt

In [2]:
data=pd.read_csv("Laliga.csv")

In [3]:
data.head()

Unnamed: 0       Unnamed: 1 Unnamed: 2 Unnamed: 3   Unnamed: 4 Unnamed: 5  \
0        Pos             Team    Seasons     Points  GamesPlayed   GamesWon   
1          1      Real Madrid         86       4385         2762       1647   
2          2        Barcelona         86       4262         2762       1581   
3          3  Atletico Madrid         80       3442         2614       1241   
4          4         Valencia         82       3386         2664       1187   

   Unnamed: 6 Unnamed: 7 Unnamed: 8    Unnamed: 9 Unnamed: 10 Unnamed: 11  \
0  GamesDrawn  GamesLost   GoalsFor  GoalsAgainst    Champion   Runner-up   
1         552        563       5947          3140          33          23   
2         573        608       5900          3114          25          25   
3         598        775       4534          3309          10           8   
4         616        861       4398          3469           6           6   

  Unnamed: 12 Unnamed: 13 Unnamed: 14 Unnamed: 15 Unnamed: 16 Unnamed: 17  \
0       Third      Fourth       Fifth       Sixth           T       Debut   
1           8           8           3           4          79        1929   
2          12          12           4           6          83        1929   
3          16           9           7           6          56        1929   
4          10          11          10           7          50     1931-32   

     Unnamed: 18   Unnamed: 19  
0  Since/LastApp  BestPosition  
1           1929             1  
2           1929             1  
3        2002-03             1  
4        1987-88             1

In [4]:
data. columns = data.iloc[0] 
     

In [5]:
data.head()

0  Pos             Team  Seasons  Points  GamesPlayed  GamesWon  GamesDrawn  \
0  Pos             Team  Seasons  Points  GamesPlayed  GamesWon  GamesDrawn   
1    1      Real Madrid       86    4385         2762      1647         552   
2    2        Barcelona       86    4262         2762      1581         573   
3    3  Atletico Madrid       80    3442         2614      1241         598   
4    4         Valencia       82    3386         2664      1187         616   

0  GamesLost  GoalsFor  GoalsAgainst  Champion  Runner-up  Third  Fourth  \
0  GamesLost  GoalsFor  GoalsAgainst  Champion  Runner-up  Third  Fourth   
1        563      5947          3140        33         23      8       8   
2        608      5900          3114        25         25     12      12   
3        775      4534          3309        10          8     16       9   
4        861      4398          3469         6          6     10      11   

0  Fifth  Sixth   T    Debut  Since/LastApp  BestPosition  
0  Fifth  Sixth   T    Debut  Since/LastApp  BestPosition  
1      3      4  79     1929           1929             1  
2      4      6  83     1929           1929             1  
3      7      6  56     1929        2002-03             1  
4     10      7  50  1931-32        1987-88             1

In [6]:
 data = data.drop(0)
data=data.reset_index(drop=True)

In [7]:
data.head()

0 Pos             Team Seasons Points GamesPlayed GamesWon GamesDrawn  \
0   1      Real Madrid      86   4385        2762     1647        552   
1   2        Barcelona      86   4262        2762     1581        573   
2   3  Atletico Madrid      80   3442        2614     1241        598   
3   4         Valencia      82   3386        2664     1187        616   
4   5  Athletic Bilbao      86   3368        2762     1209        633   

0 GamesLost GoalsFor GoalsAgainst Champion Runner-up Third Fourth Fifth Sixth  \
0       563     5947         3140       33        23     8      8     3     4   
1       608     5900         3114       25        25    12     12     4     6   
2       775     4534         3309       10         8    16      9     7     6   
3       861     4398         3469        6         6    10     11    10     7   
4       920     4631         3700        8         7    10      5     8    10   

0   T    Debut Since/LastApp BestPosition  
0  79     1929          1929            1  
1  83     1929          1929            1  
2  56     1929       2002-03            1  
3  50  1931-32       1987-88            1  
4  49     1929          1929            1

In [8]:
data

0  Pos              Team Seasons Points GamesPlayed GamesWon GamesDrawn  \
0    1       Real Madrid      86   4385        2762     1647        552   
1    2         Barcelona      86   4262        2762     1581        573   
2    3   Atletico Madrid      80   3442        2614     1241        598   
3    4          Valencia      82   3386        2664     1187        616   
4    5   Athletic Bilbao      86   3368        2762     1209        633   
..  ..               ...     ...    ...         ...      ...        ...   
56  57             Xerez       1     34          38        8         10   
57  58            Condal       1     22          30        7          8   
58  59   Atletico Tetuan       1     19          30        7          5   
59  60  Cultural Leonesa       1     14          30        5          4   
60  61            Girona       1      -           -        -          -   

0  GamesLost GoalsFor GoalsAgainst Champion Runner-up Third Fourth Fifth  \
0        563     5947         3140       33        23     8      8     3   
1        608     5900         3114       25        25    12     12     4   
2        775     4534         3309       10         8    16      9     7   
3        861     4398         3469        6         6    10     11    10   
4        920     4631         3700        8         7    10      5     8   
..       ...      ...          ...      ...       ...   ...    ...   ...   
56        20       38           66        -         -     -      -     -   
57        15       37           57        -         -     -      -     -   
58        18       51           85        -         -     -      -     -   
59        21       34           65        -         -     -      -     -   
60         -        -            -        -         -     -      -     -   

0  Sixth   T    Debut Since/LastApp BestPosition  
0      4  79     1929          1929            1  
1      6  83     1929          1929            1  
2      6  56     1929       2002-03            1  
3      7  50  1931-32       1987-88            1  
4     10  49     1929          1929            1  
..   ...  ..      ...           ...          ...  
56     -   -  2009-10       2009-10           20  
57     -   -  1956-57       1956-57           16  
58     -   -  1951-52       1951-52           16  
59     -   -  1955-56       1955-56           15  
60     -   -  2017-18       2017-18            9  

[61 rows x 20 columns]

In [9]:
data.dtypes

0
Pos              object
Team             object
Seasons          object
Points           object
GamesPlayed      object
GamesWon         object
GamesDrawn       object
GamesLost        object
GoalsFor         object
GoalsAgainst     object
Champion         object
Runner-up        object
Third            object
Fourth           object
Fifth            object
Sixth            object
T                object
Debut            object
Since/LastApp    object
BestPosition     object
dtype: object

In [10]:
data.columns


Index(['Pos', 'Team', 'Seasons', 'Points', 'GamesPlayed', 'GamesWon',
       'GamesDrawn', 'GamesLost', 'GoalsFor', 'GoalsAgainst', 'Champion',
       'Runner-up', 'Third', 'Fourth', 'Fifth', 'Sixth', 'T', 'Debut',
       'Since/LastApp', 'BestPosition'],
      dtype='object', name=0)

In [11]:
np.unique(data["Pos"])

array(['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19',
       '2', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29',
       '3', '30', '31', '32', '33', '34', '35', '36', '37', '38', '39',
       '4', '40', '41', '42', '43', '44', '45', '46', '47', '48', '49',
       '5', '50', '51', '52', '53', '54', '55', '56', '57', '58', '59',
       '6', '60', '61', '7', '8', '9'], dtype=object)

In [12]:
np.unique(data["Team"])

array(['AD Almeria', 'Alaves', 'Albacete', 'Alcoyano', 'Almeria',
       'Arenas', 'Athletic Bilbao', 'Atletico Madrid', 'Atletico Tetuan',
       'Barcelona', 'Burgos CF', 'Cadiz', 'Castellon', 'Celta Vigo',
       'Compostela', 'Condal', 'Cordoba', 'Cultural Leonesa',
       'Deportivo La Coruna', 'Eibar', 'Elche', 'Espanyol', 'Europa',
       'Extremadura', 'Getafe', 'Gimnastic', 'Girona', 'Granada',
       'Hercules', 'Jaen', 'Las Palmas', 'Leganes', 'Levante', 'Lleida',
       'Logrones', 'Malaga', 'Mallorca', 'Merida', 'Murcia', 'Numancia',
       'Osasuna', 'Oviedo', 'Pontevedra', 'Racing Santander',
       'Rayo Vallecano', 'Real Betis', 'Real Burgos', 'Real Madrid',
       'Real Sociedad', 'Real Union', 'Recreativo', 'Sabadell',
       'Salamanca', 'Sevilla', 'Sporting Gijon', 'Tenerife', 'Valencia',
       'Valladolid', 'Villarreal', 'Xerez', 'Zaragoza'], dtype=object)

In [13]:
np.unique(data["Seasons"])

array(['1', '11', '12', '13', '14', '17', '18', '2', '20', '21', '23',
       '27', '3', '33', '36', '37', '38', '4', '42', '43', '44', '45',
       '5', '51', '58', '6', '7', '70', '73', '80', '82', '86', '9'],
      dtype=object)

<h2> Task 1 Replace "-" with 0 and verify</h2>

In [14]:
data.replace("-",0,inplace=True) # Read the data set and replace dashes with 0 

In [15]:
data["points"]=data["Points"].astype(int)

In [16]:
np.unique(data['points'])

array([   0,   14,   19,   22,   34,   35,   40,   42,   52,   56,   71,
         76,   81,   83,   91,   96,  107,  132,  148,  150,  168,  188,
        190,  230,  242,  277,  285,  293,  343,  353,  375,  416,  421,
        445,  510,  538,  553,  606,  662,  667,  970, 1020, 1148, 1174,
       1314, 1351, 1389, 1416, 1471, 1789, 1814, 1884, 2109, 2573, 2792,
       2819, 3368, 3386, 3442, 4262, 4385])

In [17]:
data.drop(columns="Points",inplace=True)


In [18]:
data["GamesPlayed"]=data["GamesPlayed"].astype(int)
np.unique(data["GamesPlayed"])

array([   0,   30,   38,   54,   68,   72,   80,   90,  108,  114,  116,
        130,  152,  160,  180,  186,  204,  228,  270,  282,  334,  346,
        380,  402,  423,  426,  448,  456,  494,  586,  628,  646,  652,
        678,  742,  988, 1096, 1192, 1255, 1318, 1428, 1458, 1466, 1530,
       1698, 1728, 1986, 2302, 2408, 2614, 2626, 2664, 2762])

In [19]:
data["GamesWon"]=data["GamesWon"].astype(int)
np.unique(data["GamesWon"])

array([   0,    5,    7,    8,   13,   17,   18,   19,   20,   21,   26,
         29,   30,   34,   35,   37,   43,   50,   52,   53,   59,   62,
         76,   82,   96,  103,  104,  113,  123,  125,  129,  145,  147,
        155,  184,  189,  203,  218,  266,  333,  367,  390,  408,  426,
        453,  463,  471,  563,  586,  606,  698,  864,  948,  990, 1187,
       1209, 1241, 1581, 1647])

In [20]:
data["GamesDrawn"]=data["GamesDrawn"].astype(int)
np.unique(data["GamesDrawn"])

array([  0,   4,   5,   6,   8,  10,  11,  13,  14,  16,  18,  21,  23,
        24,  27,  37,  44,  45,  46,  50,  56,  63,  76,  79,  81,  92,
        95, 102, 112, 127, 128, 143, 148, 149, 172, 175, 180, 242, 256,
       292, 327, 330, 336, 358, 384, 389, 392, 440, 522, 531, 552, 573,
       577, 598, 608, 616, 633])

In [21]:
data["GamesLost"]=data["GamesLost"].astype(int)
np.unique(data["GamesLost"])

array([   0,   15,   18,   19,   20,   21,   30,   33,   37,   41,   44,
         48,   52,   62,   63,   66,   78,   83,   90,   95,  110,  118,
        137,  152,  158,  174,  194,  197,  198,  202,  208,  211,  217,
        295,  298,  305,  349,  399,  487,  492,  535,  563,  565,  575,
        608,  619,  629,  639,  682,  723,  766,  775,  861,  887,  920,
       1070])

In [22]:
data["GoalsFor"]=data["GoalsFor"].astype(int)
np.unique(data["GoalsFor"])

array([   0,   34,   36,   37,   38,   51,   62,   70,   71,   97,  101,
        121,  139,  145,  153,  155,  165,  181,  199,  202,  216,  227,
        244,  285,  291,  320,  393,  419,  422,  430,  458,  492,  520,
        607,  619,  716,  750,  760,  819,  892, 1182, 1347, 1421, 1500,
       1642, 1753, 1767, 1843, 2052, 2159, 2278, 2683, 3228, 3609, 3680,
       4398, 4534, 4631, 5900, 5947])

In [23]:
data["GoalsAgainst"]=data["GoalsAgainst"].astype(int)
np.unique(data["GoalsAgainst"])

array([   0,   55,   57,   65,   66,   85,  115,  116,  117,  131,  139,
        167,  182,  183,  184,  221,  241,  252,  253,  295,  296,  308,
        310,  366,  410,  430,  489,  581,  588,  623,  632,  633,  662,
        720,  744,  789,  992, 1022, 1050, 1088, 1157, 1371, 1746, 1763,
       1834, 1951, 2152, 2180, 2188, 2368, 2492, 2624, 2847, 3114, 3140,
       3230, 3309, 3373, 3469, 3700, 3889])

In [24]:
data["Runner-up"]

0     23
1     25
2      8
3      6
4      7
      ..
56     0
57     0
58     0
59     0
60     0
Name: Runner-up, Length: 61, dtype: object

In [25]:
data["Champion"]=data["Champion"].astype(int)
np.unique(data["Champion"])

array([ 0,  1,  2,  6,  8, 10, 25, 33])

In [26]:
data["Runner-up"]=data["Runner-up"].astype(int)
np.unique(data["Runner-up"])

array([ 0,  1,  3,  4,  5,  6,  7,  8, 23, 25])

In [27]:
data["Third"]=data["Third"].astype(int)
np.unique(data["Third"])

array([ 0,  1,  2,  3,  4,  8, 10, 12, 16])

In [28]:
data["Fourth"]=data["Fourth"].astype(int)
np.unique(data["Fourth"])

array([ 0,  1,  2,  3,  5,  8,  9, 11, 12])

In [29]:
data["Fifth"]=data["Fifth"].astype(int)
np.unique(data["Fifth"])

array([ 0,  1,  2,  3,  4,  7,  8, 10, 12])

In [30]:
data["Sixth"]=data["Sixth"].astype(int)
np.unique(data["Sixth"])

array([ 0,  1,  2,  3,  4,  5,  6,  7, 10])

In [31]:
data["T"]=data["T"].astype(int)
np.unique(data["T"])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  9, 11, 12, 14, 16, 18, 19, 32, 49,
       50, 56, 79, 83])

In [32]:
np.unique(data["Debut"])


array(['1929', '1930-31', '1931-32', '1932-33', '1933-34', '1934-35',
       '1935-36', '1939-40', '1940-41', '1941-42', '1943-44', '1944-45',
       '1945-46', '1947-48', '1948-49', '1949-50', '1950-51', '1951-52',
       '1953-54', '1955-56', '1956-57', '1959-60', '1960-61', '1961-62',
       '1962-63', '1963-64', '1971-72', '1974-75', '1977-78', '1978-79',
       '1979-80', '1987-88', '1990-91', '1991-92', '1994-95', '1995-96',
       '1996-97', '1998-99', '1999-00', '2004-05', '2007-08', '2009-10',
       '2014-15', '2016-17', '2017-18'], dtype=object)

In [33]:
np.unique(data["Since/LastApp"])

array(['1929', '1930-31', '1931-32', '1934-35', '1950-51', '1951-52',
       '1955-56', '1956-57', '1957-58', '1969-70', '1979-80', '1980-81',
       '1987-88', '1990-91', '1992-93', '1993-94', '1994-95', '1996-97',
       '1997-98', '1998-99', '2000-01', '2001-02', '2002-03', '2004-05',
       '2005-06', '2006-07', '2007-08', '2008-09', '2009-10', '2010-11',
       '2011-12', '2012-13', '2013-14', '2014-15', '2015-16', '2016-17',
       '2017-18'], dtype=object)

In [34]:
data["BestPosition"]=data["BestPosition"].astype(int)
np.unique(data["BestPosition"])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 14, 15, 16, 17, 19,
       20])

In [35]:
data.dtypes

0
Pos              object
Team             object
Seasons          object
GamesPlayed       int32
GamesWon          int32
GamesDrawn        int32
GamesLost         int32
GoalsFor          int32
GoalsAgainst      int32
Champion          int32
Runner-up         int32
Third             int32
Fourth            int32
Fifth             int32
Sixth             int32
T                 int32
Debut            object
Since/LastApp    object
BestPosition      int32
points            int32
dtype: object

<h2>Task 2 : Teams that Started Playing between 1930 - 1980</h2>


In [36]:
np.unique(data['Debut'])

array(['1929', '1930-31', '1931-32', '1932-33', '1933-34', '1934-35',
       '1935-36', '1939-40', '1940-41', '1941-42', '1943-44', '1944-45',
       '1945-46', '1947-48', '1948-49', '1949-50', '1950-51', '1951-52',
       '1953-54', '1955-56', '1956-57', '1959-60', '1960-61', '1961-62',
       '1962-63', '1963-64', '1971-72', '1974-75', '1977-78', '1978-79',
       '1979-80', '1987-88', '1990-91', '1991-92', '1994-95', '1995-96',
       '1996-97', '1998-99', '1999-00', '2004-05', '2007-08', '2009-10',
       '2014-15', '2016-17', '2017-18'], dtype=object)

In [37]:
data['Debut']=data['Debut'].replace({"1930-31":1930,'1931-32':1931,
                      '1932-33':1932,'1933-34':1933,
                       '1934-35':1935,'1935-36':1935,'1939-40':1939,'1940-41':1940,'1941-42':1941, '1943-44':1943,
                       '1944-45':1944,'1945-46':1945, '1947-48':1947, '1948-49':1948, '1949-50':1949, '1950-51':1950,
                       '1951-52':1951,'1953-54':1953, '1955-56':1955, '1956-57':1956, '1959-60':1959, '1960-61':1960,
                       '1961-62':1961,'1962-63':1962, '1963-64':1963, '1971-72':1972, '1974-75':1974, '1977-78':1977,
                       '1978-79':1978,'1979-80':1979, '1987-88':1987, '1990-91':1990, '1991-92':1991, '1994-95':1994,
                       '1995-96':1995,'1996-97':1996, '1998-99':1998, '1999-00':1999, '2004-05':2004, '2007-08':2007, 
                       '2009-10':2009,'2014-15':2014, '2016-17':2016, '2017-18':2017})
data['Debut']=data["Debut"].astype(int)

In [38]:
data

0  Pos              Team Seasons  GamesPlayed  GamesWon  GamesDrawn  \
0    1       Real Madrid      86         2762      1647         552   
1    2         Barcelona      86         2762      1581         573   
2    3   Atletico Madrid      80         2614      1241         598   
3    4          Valencia      82         2664      1187         616   
4    5   Athletic Bilbao      86         2762      1209         633   
..  ..               ...     ...          ...       ...         ...   
56  57             Xerez       1           38         8          10   
57  58            Condal       1           30         7           8   
58  59   Atletico Tetuan       1           30         7           5   
59  60  Cultural Leonesa       1           30         5           4   
60  61            Girona       1            0         0           0   

0   GamesLost  GoalsFor  GoalsAgainst  Champion  Runner-up  Third  Fourth  \
0         563      5947          3140        33         23      8       8   
1         608      5900          3114        25         25     12      12   
2         775      4534          3309        10          8     16       9   
3         861      4398          3469         6          6     10      11   
4         920      4631          3700         8          7     10       5   
..        ...       ...           ...       ...        ...    ...     ...   
56         20        38            66         0          0      0       0   
57         15        37            57         0          0      0       0   
58         18        51            85         0          0      0       0   
59         21        34            65         0          0      0       0   
60          0         0             0         0          0      0       0   

0   Fifth  Sixth   T  Debut Since/LastApp  BestPosition  points  
0       3      4  79   1929          1929             1    4385  
1       4      6  83   1929          1929             1    4262  
2       7      6  56   1929       2002-03             1    3442  
3      10      7  50   1931       1987-88             1    3386  
4       8     10  49   1929          1929             1    3368  
..    ...    ...  ..    ...           ...           ...     ...  
56      0      0   0   2009       2009-10            20      34  
57      0      0   0   1956       1956-57            16      22  
58      0      0   0   1951       1951-52            16      19  
59      0      0   0   1955       1955-56            15      14  
60      0      0   0   2017       2017-18             9       0  

[61 rows x 20 columns]

In [39]:
debut=data[["Team","Debut"]]

In [40]:
debut

0               Team  Debut
0        Real Madrid   1929
1          Barcelona   1929
2    Atletico Madrid   1929
3           Valencia   1931
4    Athletic Bilbao   1929
..               ...    ...
56             Xerez   2009
57            Condal   1956
58   Atletico Tetuan   1951
59  Cultural Leonesa   1955
60            Girona   2017

[61 rows x 2 columns]

In [41]:
data2=debut.loc[debut['Debut']>=1930]

In [42]:
data2=data2.reset_index()

In [43]:
data2.drop(columns=["index"],inplace=True)

In [44]:
data2

0                  Team  Debut
0              Valencia   1931
1               Sevilla   1935
2              Zaragoza   1939
3            Real Betis   1932
4   Deportivo La Coruna   1941
5            Celta Vigo   1939
6            Valladolid   1948
7        Sporting Gijon   1944
8               Osasuna   1935
9                Malaga   1949
10               Oviedo   1933
11             Mallorca   1960
12           Las Palmas   1951
13           Villarreal   1998
14              Granada   1941
15       Rayo Vallecano   1977
16                Elche   1959
17               Getafe   2004
18             Hercules   1935
19             Tenerife   1961
20               Murcia   1940
21               Alaves   1930
22              Levante   1963
23            Salamanca   1974
24             Sabadell   1943
25                Cadiz   1977
26             Logrones   1987
27            Castellon   1941
28             Albacete   1991
29              Almeria   2007
30              Cordoba   1962
31           Compostela   1994
32           Recreativo   1978
33            Burgos CF   1972
34           Pontevedra   1963
35             Numancia   1999
36                Eibar   2014
37          Real Burgos   1990
38            Gimnastic   1947
39          Extremadura   1996
40               Merida   1995
41             Alcoyano   1945
42                 Jaen   1953
43           AD Almeria   1979
44               Lleida   1950
45              Leganes   2016
46                Xerez   2009
47               Condal   1956
48      Atletico Tetuan   1951
49     Cultural Leonesa   1955
50               Girona   2017

In [45]:
final=data2.loc[data2['Debut']<=1980]

In [46]:
final # Result 2 Print all the teams which have started playing between 1930-1980.

0                  Team  Debut
0              Valencia   1931
1               Sevilla   1935
2              Zaragoza   1939
3            Real Betis   1932
4   Deportivo La Coruna   1941
5            Celta Vigo   1939
6            Valladolid   1948
7        Sporting Gijon   1944
8               Osasuna   1935
9                Malaga   1949
10               Oviedo   1933
11             Mallorca   1960
12           Las Palmas   1951
14              Granada   1941
15       Rayo Vallecano   1977
16                Elche   1959
18             Hercules   1935
19             Tenerife   1961
20               Murcia   1940
21               Alaves   1930
22              Levante   1963
23            Salamanca   1974
24             Sabadell   1943
25                Cadiz   1977
27            Castellon   1941
30              Cordoba   1962
32           Recreativo   1978
33            Burgos CF   1972
34           Pontevedra   1963
38            Gimnastic   1947
41             Alcoyano   1945
42                 Jaen   1953
43           AD Almeria   1979
44               Lleida   1950
47               Condal   1956
48      Atletico Tetuan   1951
49     Cultural Leonesa   1955

<h2> Task 3 Print the list of teams which came Top 5 in terms of points <h2>

In [47]:
data3=data[['Team','points']]

In [48]:
data3=data3.sort_values(by='points',ascending=False)


In [49]:
data3.head() # result 3 Print the list of teams which came Top 5 in terms of points

0             Team  points
0      Real Madrid    4385
1        Barcelona    4262
2  Atletico Madrid    3442
3         Valencia    3386
4  Athletic Bilbao    3368

<h2> TASK 4   : Write a function with name “Goal_diff_count” which should return all the teams with their Goal Differences. Using the same function, find the team which has maximum and minimum goal difference. </h2>

<h2>Goal_diff_count = GoalsFor - GoalsAgainst </h2>

In [50]:
def Goal_diff_count():
    my_data=data[['Team','GoalsFor','GoalsAgainst']]
    my_data=my_data.reset_index(drop=True)
    my_data['Goal_diff_count'] = data['GoalsFor'] - data['GoalsAgainst']
    maxi=my_data['Goal_diff_count'].max()
    mini=my_data['Goal_diff_count'].min()
    print(my_data)
    print(f'Maximum Goal Difference is {maxi}')
    print(f'Minimum Goal Difference is {mini}')

In [51]:
Goal_diff_count()

0               Team  GoalsFor  GoalsAgainst  Goal_diff_count
0        Real Madrid      5947          3140             2807
1          Barcelona      5900          3114             2786
2    Atletico Madrid      4534          3309             1225
3           Valencia      4398          3469              929
4    Athletic Bilbao      4631          3700              931
..               ...       ...           ...              ...
56             Xerez        38            66              -28
57            Condal        37            57              -20
58   Atletico Tetuan        51            85              -34
59  Cultural Leonesa        34            65              -31
60            Girona         0             0                0

[61 rows x 4 columns]
Maximum Goal Difference is 2807
Minimum Goal Difference is -525


<h2>TASK 5: Create a new column with name “Winning Percent” and append it to the data set.</h2>

<h2>Percentage of Winning = (GamesWon / GamesPlayed)*100</h2>

<h2>If there are any numerical error, replace it with 0%</h2>

<h2>Print the top 5 teams which has the highest Winning percentage</h2>

In [52]:
Winningpercent=(data['GamesWon'] / data['GamesPlayed'])*100
data['Winning Percent']= Winningpercent

In [53]:
data['Winning Percent']=data['Winning Percent'].fillna(0)

In [54]:
data

0  Pos              Team Seasons  GamesPlayed  GamesWon  GamesDrawn  \
0    1       Real Madrid      86         2762      1647         552   
1    2         Barcelona      86         2762      1581         573   
2    3   Atletico Madrid      80         2614      1241         598   
3    4          Valencia      82         2664      1187         616   
4    5   Athletic Bilbao      86         2762      1209         633   
..  ..               ...     ...          ...       ...         ...   
56  57             Xerez       1           38         8          10   
57  58            Condal       1           30         7           8   
58  59   Atletico Tetuan       1           30         7           5   
59  60  Cultural Leonesa       1           30         5           4   
60  61            Girona       1            0         0           0   

0   GamesLost  GoalsFor  GoalsAgainst  Champion  ...  Third  Fourth  Fifth  \
0         563      5947          3140        33  ...      8       8      3   
1         608      5900          3114        25  ...     12      12      4   
2         775      4534          3309        10  ...     16       9      7   
3         861      4398          3469         6  ...     10      11     10   
4         920      4631          3700         8  ...     10       5      8   
..        ...       ...           ...       ...  ...    ...     ...    ...   
56         20        38            66         0  ...      0       0      0   
57         15        37            57         0  ...      0       0      0   
58         18        51            85         0  ...      0       0      0   
59         21        34            65         0  ...      0       0      0   
60          0         0             0         0  ...      0       0      0   

0   Sixth   T  Debut  Since/LastApp BestPosition  points  Winning Percent  
0       4  79   1929           1929            1    4385        59.630702  
1       6  83   1929           1929            1    4262        57.241130  
2       6  56   1929        2002-03            1    3442        47.475134  
3       7  50   1931        1987-88            1    3386        44.557057  
4      10  49   1929           1929            1    3368        43.772629  
..    ...  ..    ...            ...          ...     ...              ...  
56      0   0   2009        2009-10           20      34        21.052632  
57      0   0   1956        1956-57           16      22        23.333333  
58      0   0   1951        1951-52           16      19        23.333333  
59      0   0   1955        1955-56           15      14        16.666667  
60      0   0   2017        2017-18            9       0         0.000000  

[61 rows x 21 columns]

In [55]:
data_according_to_winpercen=data.sort_values(by="Winning Percent",ascending=False)

In [56]:
data_according_to_winpercen.head()

0 Pos             Team Seasons  GamesPlayed  GamesWon  GamesDrawn  GamesLost  \
0   1      Real Madrid      86         2762      1647         552        563   
1   2        Barcelona      86         2762      1581         573        608   
2   3  Atletico Madrid      80         2614      1241         598        775   
3   4         Valencia      82         2664      1187         616        861   
4   5  Athletic Bilbao      86         2762      1209         633        920   

0  GoalsFor  GoalsAgainst  Champion  ...  Third  Fourth  Fifth  Sixth   T  \
0      5947          3140        33  ...      8       8      3      4  79   
1      5900          3114        25  ...     12      12      4      6  83   
2      4534          3309        10  ...     16       9      7      6  56   
3      4398          3469         6  ...     10      11     10      7  50   
4      4631          3700         8  ...     10       5      8     10  49   

0  Debut  Since/LastApp BestPosition  points  Winning Percent  
0   1929           1929            1    4385        59.630702  
1   1929           1929            1    4262        57.241130  
2   1929        2002-03            1    3442        47.475134  
3   1931        1987-88            1    3386        44.557057  
4   1929           1929            1    3368        43.772629  

[5 rows x 21 columns]

<h2>TASK 6: Group teams based on their “Best position” and print the sum of their points for all positions </h2>

In [57]:
data.groupby('BestPosition')['points'].sum()

BestPosition
1     27933
2      6904
3      5221
4      6563
5      1884
6      2113
7      1186
8      1134
9        96
10      450
11      445
12      511
14       71
15       14
16       81
17      266
19       81
20       34
Name: points, dtype: int32

<h2>THANK YOU</h2>